# Source: react-quickstart/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-01-20T10:34:49Z"
  deletionTimestamp: null
  name: 'react-quickstart-0.1.2'
  namespace: jx-production
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: release 0.1.2
      sha: 867084ec55527eed1dbf4c7394bd37a6df8ef749
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: add variables
      sha: eeb415423599f6b9e292170baa56754a5a4fb390
    - author:
        email: gil@tikalk.com
        name: gilShin
      branch: master
      committer:
        email: noreply@github.com
        name: GitHub
      message: Update README.md
      sha: 9fe01644afded34f03dc6525748565282e6cc0c1
  gitHttpUrl: https://github.com/gilShin/react-quickstart
  gitOwner: gilShin
  gitRepository: react-quickstart
  name: 'react-quickstart'
  releaseNotesURL: https://github.com/gilShin/react-quickstart/releases/tag/v0.1.2
  version: v0.1.2
status: {}
