filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-staging
repositories:
- name: dev
  url: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts/
releases:
- chart: dev/golang-http
  version: 0.0.6
  name: golang-http
  values:
  - jx-values.yaml
- chart: dev/rails-shopping-cart
  version: 0.0.4
  name: rails-shopping-cart
  values:
  - jx-values.yaml
- chart: dev/react-quickstart
  version: 0.1.2
  name: react-quickstart
  values:
  - jx-values.yaml
- chart: dev/node-http
  version: 1.0.1
  name: node-http
templates: {}
renderedvalues: {}
