apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        gilShin/cars-rest-api: true
        gilShin/golang-http: true
        gilShin/jx3-demo2: true
        gilShin/rails-shopping-cart: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        gilShin/cars-rest-api: merge
        gilShin/golang-http: merge
        gilShin/jx3-demo2: merge
        gilShin/rails-shopping-cart: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - gilShin/jx3-demo2
        - gilShin/cars-rest-api
        - gilShin/golang-http
        - gilShin/rails-shopping-cart
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - gilShin/jx3-demo2
        - gilShin/cars-rest-api
        - gilShin/golang-http
        - gilShin/rails-shopping-cart
      target_url: http://dashboard-jx.192.168.99.100.nip.io
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
