filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-production
repositories:
- name: dev
  url: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts/
releases:
- chart: dev/golang-http
  version: 0.0.6
  name: golang-http
  values:
  - jx-values.yaml
- chart: dev/rails-shopping-cart
  version: 0.0.4
  name: rails-shopping-cart
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
