# Source: golang-http/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-01-14T10:23:36Z"
  deletionTimestamp: null
  name: 'golang-http-0.0.6'
  namespace: jx-production
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: release 0.0.6
      sha: ced045251a99b793b1fbd456660612e32788e0c0
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: add variables
      sha: 2012ba5dfb4483e5aaea3098f70f528ff4eb83d7
    - author:
        email: gil@anodot.com
        name: Gil Shinar
      branch: master
      committer:
        email: gil@anodot.com
        name: Gil Shinar
      message: |
        test laptop pr
      sha: a48af77254447d8a1d769bf4dbc85006b113e1e3
  gitHttpUrl: https://github.com/gilShin/golang-http
  gitOwner: gilShin
  gitRepository: golang-http
  name: 'golang-http'
  releaseNotesURL: https://github.com/gilShin/golang-http/releases/tag/v0.0.6
  version: v0.0.6
status: {}
